---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: konsear-azure-managed-disk
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: default
  resources:
    requests:
      storage: 8Gi
