
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: konsear
  labels:
    app: konsear-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
