---
apiVersion: v1
kind: Service
metadata:
  name: konsear-svc
  labels:
    run: konsear
spec:
  type: NodePort
  ports:
  - nodePort: 30095
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: konsear

