apiVersion: v1
kind: Pod
metadata:
  name: konsear-myadmin
  labels:
    name: konsear-myadmin
spec:
  containers:
    - name: konsear-phpmyadmin
      image: phpmyadmin/phpmyadmin
      env:
        - name: PMA_ARBITRARY
          value: "1"
        - name: PMA_HOST
          value: 172.17.0.19
          #        - name: PMA_VERBOSE
          #value: test
          #- name: PMA_USER
          #value: root"
          #- name: PMA_PASSWORD
          #value: password
        - name: PMA_PORT
          value: "3306"
      ports:
        - containerPort: 80
          name: konsear-myadmin
